version: "3.9"
services:
  api:
    build: .
    depends_on:
      - db
    ports:
      - '5000:5000'
    env_file: ./.env
    volumes:
      - .:/usr/src/app


  db:
    image: postgres:12.1-alpine
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=marryage_db
      - PGDATA=/var/lib/postgresql/data/
    volumes:
      - ./.docker/pgdata:/var/lib/postgresql/data/


  pgadmin:
    image: dpage/pgadmin4
    logging:
      driver: "none"
    ports:
      - '8080:80'
    environment:
      - PGADMIN_DEFAULT_EMAIL=dba@marrymage.com
      - PGADMIN_DEFAULT_PASSWORD=123456

